# Generated by Django 4.0.1 on 2022-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=300)),
                ('familiya', models.CharField(max_length=300)),
                ('tug_yil', models.DateTimeField()),
                ('tel', models.IntegerField()),
                ('jins', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=200)),
            ],
        ),
    ]
